# Generated by Django 4.1.4 on 2022-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yoga", "0003_rename_payments_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
