# Generated by Django 4.1.4 on 2022-12-10 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yoga", "0004_alter_payment_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="batch",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="yoga.batch"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="yoga.batch",
            ),
        ),
    ]
