# Generated by Django 4.1.4 on 2022-12-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("yoga", "0006_payment_card_cvv_payment_card_expiry_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
            },
        ),
    ]
